### PR TITLE
feat: support CMake for Qt 6

### PR DESCRIPTION
**Pull request by Nerixyz**
As the qmake based build doesn't work with Qt ^6.5.0, I added a CMake build. The build process is identical to most CMake projects (see readme):

```shell
cmake -B build -G Ninja
ninja -C build
```

Building zlib with CMake caused `zconf.h` to be deleted and moved to `zconf.h.included`. I applied the fixes mentioned in https://github.com/madler/zlib/issues/133 as a patch (running `get_libs.sh` should yield the exact same state - i.e. no changed files).

### CODE REVIEW

**Comment by jdpurcell** [comment]
@jurplel I tried making the kimageformats-binaries script work with this PR ([commit here](https://github.com/jdpurcell/kimageformats-binaries/commit/517b4f2d7f217247eff204280068fd40f277f6ff)) and was kind of successful (I didn't feel like messing with the macOS universal binary stuff), but I made the following modifications to QtApng on top of this PR:

1. `/src/3rdparty/zlib/src/CMakeLists.txt` references `zlib1.rc` which isn't in the repo, so [I added it](https://github.com/jdpurcell/QtApng/commit/b4b47e8292450c67b554e25b3f9b10feeda02c74).
2. The name of the output binary was different than before (e.g. `ApngImagePlugin.dll` vs `qapng.dll`), so [I made it use the old name](https://github.com/jdpurcell/QtApng/commit/6c3041c764771e10981cbb8eb6b1876b710f123d).

**Comment by jdpurcell** [comment]
@Nerixyz Thank you for including those fixes! All the work you put into making this build with CMake is much appreciated.

@jurplel I now have this fully integrated in my kimageformats-binaries fork, including the macOS universal binary ([commit here](https://github.com/jdpurcell/kimageformats-binaries/commit/c51a381ee48ccbb9379df0b7ec72c5f59ba14b29)). I've tested the new QtApng plugin in qView on both macOS and Windows and it works fine.

**Comment by jurplel** [comment]
I am experiencing a couple of issues when testing locally:
- The `qmake` build doesn't seem to work:
```
gcc -c -pipe -O2 -fPIC -std=gnu11 -fvisibility=hidden -w -fno-exceptions -flto -fno-fat-lto-objects -DQT_NO_LINKED_LIST -DQT_DEPRECATED_WARNINGS -DQT_ASCII_CAST_WARNINGS -DQT_NO_NARROWING_CONVERSIONS_IN_CONNECT -DQT_NO_DYNAMIC_CAST -DQT_NO_EXCEPTIONS -D_LARGEFILE64_SOURCE -D_LARGEFILE_SOURCE -I. -Isrc -I/usr/lib/qt/mkspecs/linux-g++ -o .obj/adler32.o src/adler32.c
In file included from src/zutil.h:22,
                 from src/adler32.c:8:
src/zlib.h:1468:32: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Z_ARG’
 1468 | ZEXTERN int ZEXPORTVA gzprintf Z_ARG((gzFile file, const char *format, ...));
      |                                ^~~~~
src/zlib.h:1902:44: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘Z_ARG’
 1902 | ZEXTERN int            ZEXPORTVA gzvprintf Z_ARG((gzFile file,
      |                                            ^~~~~
make[3]: *** [Makefile:677: .obj/adler32.o] Error 1
make[3]: Leaving directory '/home/bowad/dev/QtApng/src/3rdparty/zlib'
make[2]: *** [Makefile:48: sub-zlib-make_first] Error 2
make[2]: Leaving directory '/home/bowad/dev/QtApng/src/3rdparty'
make[1]: *** [Makefile:73: sub-3rdparty-make_first] Error 2
make[1]: Leaving directory '/home/bowad/dev/QtApng/src'
make: *** [Makefile:49: sub-src-make_first] Error 2
```
- The `cmake` build doesn't work on my local machine
```
/usr/bin/ld: ../../../3rdparty/libpng/src/libpng16.a(pngpread.c.o): warning: relocation against `png_push_fill_buffer' in read-only section `.text'
/usr/bin/ld: ../../../3rdparty/libpng/src/libpng16.a(png.c.o): relocation R_X86_64_PC32 against symbol `png_zalloc' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: final link failed: bad value
collect2: error: ld returned 1 exit status
make[2]: *** [src/plugins/imageformats/apng/CMakeFiles/ApngImagePlugin.dir/build.make:152: plugins/imageformats/libqapng.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:1073: src/plugins/imageformats/apng/CMakeFiles/ApngImagePlugin.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```
- I might be mistaken about this, but I think that `make clean` did not clean up everything. I think some of the files in the `src/3rdparty` subdirectory stuck around.

We can stop supporting the `qmake` build, as long as the `cmake` works on older Qt versions.

**Comment by jdpurcell** [comment]
@jurplel I didn't try to build locally, just through GitHub Actions on kimageformats-binaries. CMake worked fine there but only w/ Qt >= 6.5 I believe. So I kept QMake for the older versions, but if you notice in the commit I mentioned yesterday, that script was pulling an entirely different Git branch for QMake because it wouldn't work against this PR. I figured it out later though, [fixed it here](https://github.com/jdpurcell/QtApng/commit/7dcf2a63b674bd7b3f70d4904f6bb39b62bf62ed), and then was able to [clean up](https://github.com/jdpurcell/kimageformats-binaries/commit/1d20b6a592202de8ec127660ea2b7e2b54f88c1f) the kimageformats-binaries build script a bit.

**Comment by jurplel** [comment]
Why doesn't the CMake build work on Qt5? I feel that the ideal way to do this change is to remove qmake support.

**Comment by Nerixyz** [comment]
Updated everything to use CMake. For Qt 5 there's no `qt5_add_plugin`, so I copied the one from Qt 6 and trimmed it down to the stuff we actually use. I didn't update the CI, as it needs a major overhaul (not just qmake → cmake). If you want me to update the CI, I could try that.

I noticed one test not passing. The following line fails for the invalid image. `error()` returns `UnknownError` on both Qt 5 and 6. https://github.com/jurplel/QtApng/blob/0dff8019827b6041efdd5ab28bbcaca5de7897bc/tests/auto/apng/apngPlugin/tst_apngplugin.cpp#L71

**Comment by jdpurcell** [comment]
I was able to get everything building on CMake now, [Actions run here](https://github.com/jdpurcell/kimageformats-binaries/actions/runs/8973939291), I didn't try using the resulting binaries yet though.

1. Qt's docs for [qt_add_plugin](https://doc.qt.io/qt-6/qt-add-plugin.html) says _the ability to set sources were introduced in Qt 6.5_, so I had to make [this change](https://github.com/jdpurcell/QtApng/commit/368c8250291cc4b56f5036544cf6ab1ab9b75bcc) to compile with Qt 6.0-6.4.
2. I had to pass -DCMAKE_POSITION_INDEPENDENT_CODE=ON to get it compiling for Linux, otherwise got an error like `/usr/bin/ld: src/3rdparty/libpng/src/libpng16.a(pngerror.c.o): relocation R_X86_64_PC32 against symbol 'stderr@@GLIBC_2.2.5' can not be used when making a shared object; recompile with -fPIC`. No idea if that's the proper/safe fix (I'm new to building C++ stuff 😄), but it fixed the build at least.

**Comment by Nerixyz** [comment]
I'm guessing `png_static` and `zlibstatic` don't have PIC enabled, since it's only on for SHARED and MODULE targets. Not 100% sure what the idiomatic solution for this is. I don't want to force people to enable `CMAKE_POSITION_INDEPENDENT_CODE` for the entire project.

**Comment by Nerixyz** [comment]
https://github.com/Nerixyz/QtApng/pull/1 added a mini CI. It doesn't build with Qt 5.15.2 on macOS, because it doesn't have universal binaries and because of libpng we can't use `CMAKE_OSX_ARCHITECTURES`.

**Comment by jdpurcell** [comment]
Oo nice! If you're looking for another challenge, I wonder if it would build with the latest libpng/zlib. I updated those in my fork, but ran into issues getting libpng to detect/use zlib and had to do this [probably not great patch](https://github.com/jdpurcell/QtApng/blob/7dcf2a63b674bd7b3f70d4904f6bb39b62bf62ed/src/3rdparty/libpng/fix-cmake-policy.patch) to get it working. If I understand correctly, libpng wants ZLIB_ROOT set now but I couldn't figure it out.

**Comment by Nerixyz** [comment]
> If I understand correctly, libpng wants ZLIB_ROOT set now but I couldn't figure it out.

The `_ROOT` variables are mostly for making CMake discover already built libraries. CMake's internal [`FindZLIB.cmake`](https://cmake.org/cmake/help/latest/module/FindZLIB.html) to find the build. But we haven't built ZLib yet. What I did in https://github.com/Nerixyz/QtApng/compare/ci/update...Nerixyz:QtApng:feat/update-libpng was to alias `ZLIB::ZLIB` to `zlibstatic`. Since libpng only uses `target_link_libraries` (not any exposed variables) this works fine.

**Comment by jurplel** [comment]
Really excellent work!!

**Pull request merged**
